# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddperson():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addperson(self):
    self.driver.get("https://kikkare.eu.pythonanywhere.com/")
    self.driver.set_window_size(1600, 1200)
    self.driver.find_element(By.LINK_TEXT, "Persons").click()
    self.driver.find_element(By.LINK_TEXT, "Create a new person").click()
    self.driver.find_element(By.ID, "id_first_name").click()
    self.driver.find_element(By.ID, "id_first_name").send_keys("Johan")
    self.driver.find_element(By.ID, "id_last_name").send_keys("Doe")
    self.driver.find_element(By.ID, "id_email").send_keys("jd@gmail.com")
    self.driver.find_element(By.ID, "id_phone").send_keys("+122334455")
    self.driver.find_element(By.ID, "id_address").send_keys("jdroad 1")
    self.driver.find_element(By.ID, "id_city").send_keys("NYC")
    self.driver.find_element(By.ID, "id_province").send_keys("NY")
    self.driver.find_element(By.ID, "id_country").send_keys("US")
    self.driver.find_element(By.ID, "id_country").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Venues").click()
  
