# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchlogout():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchlogout(self):
    self.driver.get("https://kikkare.eu.pythonanywhere.com/")
    self.driver.set_window_size(1600, 1200)
    self.driver.find_element(By.LINK_TEXT, "Persons").click()
    self.driver.find_element(By.LINK_TEXT, "Search").click()
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").send_keys("j")
    self.driver.find_element(By.CSS_SELECTOR, ".fa-eye").click()
    self.driver.find_element(By.LINK_TEXT, "KikkareX").click()
    self.driver.find_element(By.LINK_TEXT, "Sign out").click()
  
