# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChangevenue():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_changevenue(self):
    self.driver.get("https://kikkare.eu.pythonanywhere.com/")
    self.driver.set_window_size(1600, 1200)
    self.driver.find_element(By.LINK_TEXT, "Persons").click()
    self.driver.find_element(By.LINK_TEXT, "Venues").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .fa").click()
    self.driver.find_element(By.LINK_TEXT, "Update venue").click()
    self.driver.find_element(By.ID, "id_province").click()
    self.driver.find_element(By.ID, "id_province").send_keys("Uusimaa")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-info").click()
  
